SecRule REQUEST_FILENAME "@beginsWith /socket.io/" \
    "id:1000,phase:1,pass,nolog,setvar:'tx.allowed_request_content_type=|application/x-www-form-urlencoded| |multipart/form-data| |application/json| |text/plain|'"

SecRule REQUEST_FILENAME "@rx ^/api/auth/(login|register)$" \
    "id:1001,phase:1,pass,nolog,ctl:ruleRemoveTargetByTag=OWASP_CRS;ARGS:json.password"

SecRule REQUEST_FILENAME "@streq /api/users/me/password" \
    "id:1002,phase:1,pass,nolog,ctl:ruleRemoveTargetByTag=OWASP_CRS;ARGS:json.oldPassword,ctl:ruleRemoveTargetByTag=OWASP_CRS;ARGS:json.newPassword"

SecAction "id:1003,phase:1,pass,nolog,setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PATCH DELETE'"
