Include /etc/nginx/modsecurity.conf
SecAuditLogFormat JSON

Include /etc/modsecurity/crs/crs-setup.conf
Include /etc/nginx/modsec/exclusions.conf
Include /usr/share/modsecurity-crs/rules/*.conf
Include /etc/modsecurity/crs/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
SecRuleEngine On