export const ErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_OR_EMAIL_ALREADY_TAKEN: 'USERNAME_OR_EMAIL_ALREADY_TAKEN',
  NO_DATA_UPDATED: 'NO_DATA_UPDATED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
