export const ErrorCodes = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NO_DATA_UPDATED: 'NO_DATA_UPDATED',
  USERNAME_OR_EMAIL_ALREADY_TAKEN: 'USERNAME_OR_EMAIL_ALREADY_TAKEN',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  MISSING_FILE: 'MISSING_FILE',
} as const;
